### ISSUE TITLE
git diff version.py failing

### ISSUE THREAD

**Issue by tbarron** [tbarron/gitr#3]
Traceback (most recent call last):
  File "/ccs/home/tpb/.local/bin/gitr", line 11, in <module>
    sys.exit(main())
  File "/ccs/home/tpb/.local/lib/python2.6/site-packages/gitr/**init**.py", line 83, in main
    dispatch(o)
  File "/ccs/home/tpb/.local/lib/python2.6/site-packages/gitr/**init**.py", line 91, in dispatch
    func(o)
  File "/ccs/home/tpb/.local/lib/python2.6/site-packages/gitr/**init**.py", line 155, in gitr_bv
    version_diff(repo, target)
  File "/ccs/home/tpb/.local/lib/python2.6/site-packages/gitr/**init**.py", line 226, in version_diff
    txt = repo.git.diff(target)
  File "/usr/lib/python2.6/site-packages/git/cmd.py", line 227, in <lambda>
    return lambda _args, *_kwargs: self._call_process(name, _args, *_kwargs)
  File "/usr/lib/python2.6/site-packages/git/cmd.py", line 456, in _call_process
    return self.execute(call, **_kwargs)
  File "/usr/lib/python2.6/site-packages/git/cmd.py", line 377, in execute
    raise GitCommandError(command, status, stderr_value)
git.exc.GitCommandError: 'git diff version.py' returned exit status 128: fatal: ambiguous argument 'version.py': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions

**Comment by tbarron** [comment]
This is fixed in version 0.0.1.34

**Comment by tbarron** [comment]
Issue has been fixed. Closing.
